### PR TITLE
prepare for publication

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Test using:
USE FILE FROM COMMENT BELOW

Preparation for publication on Marketplace

### CODE REVIEW

**Comment by emarc** [comment]
It's called "Visual Studio Code" or "VS Code" for short – this should be in all places (not e.g "VSCode").

**Review by emarc — DISMISSED** [review]
LGTM, here are findings (maybe split into separate issues):

1. When using Theme Editor, a save dialog is always displayed https://d.pr/v/cvXvP4
2. When a file is modified while it's open in VS Code, but not the topmost editor, the file is closed. It should remain open (and potentially we should open any files we edit and keep them open) https://d.pr/v/PaIk1g
3. Undo not available from Copilot. This makes it hard to undo, especially since files are not open in the editor -> you don't even know what was changed.
4. If a file has an unsaved change in VS Code, that change is silently discarded / overwritten if Copilot changes the file. This is a bit of a problem to thing about; we could a) silently overwriting b) warn and overwrite c) ask and block until user decides d) save changes, then overwrite e) save changes then overwrite + warn. E or B seems to have the best UX, D ok?

Any or all of these could be split into separate issues, the first is maybe the most pressing.

**Comment by MarcinVaadin** [comment]
Fixes 1 and 2:

[vaadin-vscode-1.0.0.vsix.zip](https://github.com/vaadin/vscode-plugin/files/14864096/vaadin-vscode-1.0.0.vsix.zip)

**Review by emarc — APPROVED** [review]
LGTM

**Pull request merged**
