### PR TITLE
feat: project starter

### PR DESCRIPTION
**Pull request by MarcinVaadin**
## Description

Vaadin project generator based on https://github.com/marcushellberg/luoja

Use CMD + Shift + P to open command window, type "Vaadin" and pick appropriate command. Then follow inputs.

image

### CODE REVIEW

**Review by abdullahtellioglu — COMMENTED** [review]
- Selecting the project folder should be the last step as that way is more intuitive.
- Folder name should be validated. e.g. . should not be allowed as project name
- Escaping does not cancel the project generation flow. Press escape on project name state and flow continues

**Comment by abdullahtellioglu** [comment]
- Folder name should be validated. e.g. `.` should not be allowed as project name 
- Escaping does not cancel the project generation flow. Press escape on project name state and flow continues

**Comment by MarcinVaadin** [comment]
> Selecting the project folder should be the last step as that way is more intuitive.

Indeed, specially that label is "Create here".

> Folder name should be validated. e.g. . should not be allowed as project name

Distinguished Project Name from Artifact Id. Artifact id is kebbab-cased project name by default with a-z 0-9 - _ validation.

> Escaping does not cancel the project generation flow. Press escape on project name state and flow continues

Removed default value "untitled" not to confuse anyone.

**Comment by abdullahtellioglu** [comment]
Entering `.` as a project name should not be allowed. Currently, it is allowed and nothing happens when you finish the flow

**Comment by MarcinVaadin** [comment]
Added validation for `.` at beginning and end of input. There is no point of covering every case, user should notice that it is also a directory name.

**Pull request merged**
